# Generated by Django 3.2 on 2023-04-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ('name',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('name',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='tagsrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Тэг для рецепта', 'verbose_name_plural': 'Теги для рецептов'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'verbose_name': 'Единицу измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.RemoveField(
            model_name='ingredientsrecipe',
            name='ingredient',
        ),
        migrations.CreateModel(
            name='IngredientsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients')),
            ],
            options={
                'verbose_name': 'Кол-во ингредиета для рецепта',
                'verbose_name_plural': 'Кол-во ингредиетов для рецептов',
                'ordering': ('ingredient',),
            },
        ),
        migrations.AddField(
            model_name='ingredientsrecipe',
            name='ingredient_amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientsamount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientsRecipe', to='recipes.IngredientsAmount'),
        ),
    ]
