# Generated by Django 2.2.19 on 2023-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
