# Generated by Django 3.2 on 2023-04-06 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписку на автора',
                'verbose_name_plural': 'Подписки на авторов',
                'ordering': ('user',),
            },
        ),
        migrations.AddConstraint(
            model_name='followuser',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_fail'),
        ),
        migrations.AddConstraint(
            model_name='followuser',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='follow_to_yourrself'),
        ),
    ]
